### ISSUE TITLE
Invalid link in readme

### ISSUE THREAD

**Issue by Shoozza** [ligurio/luzer#17]
This link points to a non extant repository:
https://github.com/ligurio/lua-stdlib-tests

Was it renamed?

Similar named repositories:
https://github.com/ligurio/lua-c-api-tests
https://github.com/ligurio/lua-c-api-corpus

**Comment by ligurio** [comment]
> This link points to a non extant repository:
> https://github.com/ligurio/lua-stdlib-tests

It is actually existed, but not publicly available.

**Comment by Shoozza** [comment]
Still in the readme it says:

See tests that uses luzer library in:

    Tarantool Lua API tests, https://github.com/ligurio/tarantool-lua-api-tests
    Lua standard library tests, https://github.com/ligurio/lua-stdlib-tests
    https://github.com/ligurio/snippets/tree/master/luzer-tests
    
 why is it mentioned if the repo is secret?

**Comment by ligurio** [comment]
> This link points to a non extant repository:
https://github.com/ligurio/lua-stdlib-tests

The tests moved to https://github.com/ligurio/lua-c-api-tests/tree/0508724910b252010ae5f6bcaef0e54cf198cf5b/tests/lapi
